// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Transport.Infrastructure.Data;

#nullable disable

namespace Transport.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TransportDbContext))]
    partial class TransportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Transport.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Transport.Domain.Entities.DriverProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentLat")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("CurrentLng")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DriverProfiles");
                });

            modelBuilder.Entity("Transport.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentBranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DestinationBranchId")
                        .HasColumnType("integer");

                    b.Property<int>("OriginBranchId")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentBranchId");

                    b.HasIndex("DestinationBranchId");

                    b.HasIndex("OriginBranchId");

                    b.HasIndex("TrackingNumber")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Transport.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DestinationBranchId")
                        .HasColumnType("integer");

                    b.Property<int>("DriverProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LoadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OriginBranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DestinationBranchId");

                    b.HasIndex("DriverProfileId");

                    b.HasIndex("OriginBranchId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Transport.Domain.Entities.TripProduct", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("TripId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("TripProducts");
                });

            modelBuilder.Entity("Transport.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Transport.Domain.Entities.DriverProfile", b =>
                {
                    b.HasOne("Transport.Domain.Entities.User", "User")
                        .WithOne("DriverProfile")
                        .HasForeignKey("Transport.Domain.Entities.DriverProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Transport.Domain.Entities.Product", b =>
                {
                    b.HasOne("Transport.Domain.Entities.Branch", "CurrentBranch")
                        .WithMany("ProductsAtBranch")
                        .HasForeignKey("CurrentBranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Transport.Domain.Entities.Branch", "DestinationBranch")
                        .WithMany("DestinationProducts")
                        .HasForeignKey("DestinationBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Transport.Domain.Entities.Branch", "OriginBranch")
                        .WithMany("OriginProducts")
                        .HasForeignKey("OriginBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentBranch");

                    b.Navigation("DestinationBranch");

                    b.Navigation("OriginBranch");
                });

            modelBuilder.Entity("Transport.Domain.Entities.Trip", b =>
                {
                    b.HasOne("Transport.Domain.Entities.Branch", "DestinationBranch")
                        .WithMany("DestinationTrips")
                        .HasForeignKey("DestinationBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Transport.Domain.Entities.DriverProfile", "DriverProfile")
                        .WithMany("Trips")
                        .HasForeignKey("DriverProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Transport.Domain.Entities.Branch", "OriginBranch")
                        .WithMany("OriginTrips")
                        .HasForeignKey("OriginBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationBranch");

                    b.Navigation("DriverProfile");

                    b.Navigation("OriginBranch");
                });

            modelBuilder.Entity("Transport.Domain.Entities.TripProduct", b =>
                {
                    b.HasOne("Transport.Domain.Entities.Product", "Product")
                        .WithMany("TripProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Transport.Domain.Entities.Trip", "Trip")
                        .WithMany("TripProducts")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Transport.Domain.Entities.User", b =>
                {
                    b.HasOne("Transport.Domain.Entities.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Transport.Domain.Entities.Branch", b =>
                {
                    b.Navigation("DestinationProducts");

                    b.Navigation("DestinationTrips");

                    b.Navigation("OriginProducts");

                    b.Navigation("OriginTrips");

                    b.Navigation("ProductsAtBranch");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Transport.Domain.Entities.DriverProfile", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Transport.Domain.Entities.Product", b =>
                {
                    b.Navigation("TripProducts");
                });

            modelBuilder.Entity("Transport.Domain.Entities.Trip", b =>
                {
                    b.Navigation("TripProducts");
                });

            modelBuilder.Entity("Transport.Domain.Entities.User", b =>
                {
                    b.Navigation("DriverProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
